#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StackOTiles.Resource", IsApplication=true)]

namespace StackOTiles
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int Back = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConfirmEndSession = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ConfirmExitGame = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ConfirmForceStartGame = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ConfirmLeaveSession = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ConfirmMarketplace = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ConfirmQuitGame = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Copyright = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CreateSession = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Easy = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int EndSession = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ErrorDisconnected = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ErrorGamerPrivilege = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ErrorHostEndedSession = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ErrorNetwork = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ErrorNetworkNotAvailable = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ErrorRemovedByHost = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ErrorSessionFull = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ErrorSessionNotFound = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ErrorSessionNotJoinable = 2130903059;
			
			// aapt resource value: 0x7f03003b
			public const int ErrorStoreRankings = 2130903099;
			
			// aapt resource value: 0x7f030014
			public const int ErrorTrialMode = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ErrorUnknown = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Exit = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int FindSessions = 2130903063;
			
			// aapt resource value: 0x7f030038
			public const int GameOver = 2130903096;
			
			// aapt resource value: 0x7f030018
			public const int Hard = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int HostSuffix = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int IsNotReady = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int IsReady = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int JoinInstruction = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int JoinSession = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int LeaveSession = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Level = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Loading = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int Lobby = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int Local = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int MainMenu = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int MessageBoxUsage = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int MessageGamerJoined = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int MessageGamerLeft = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int NetworkBusy = 2130903079;
			
			// aapt resource value: 0x7f030039
			public const int NoEntries = 2130903097;
			
			// aapt resource value: 0x7f030029
			public const int NoSessionsFound = 2130903081;
			
			// aapt resource value: 0x7f030028
			public const int Normal = 2130903080;
			
			// aapt resource value: 0x7f03002a
			public const int Paused = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int PlayerMatch = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int PressAToContinue = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int QuitGame = 2130903085;
			
			// aapt resource value: 0x7f03003a
			public const int Rankings = 2130903098;
			
			// aapt resource value: 0x7f03002e
			public const int ResumeGame = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int ReturnToLobby = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int Score = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int Stage = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int SystemLink = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int Time = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int ToggleReady = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int Total = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int VersusAI = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int Wins = 2130903095;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int Mono_Android_Theme_Splash = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
