//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOTiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tetatt.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Back);
				#else
				return ResourceManager.GetString("Back", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end this session?.
        /// </summary>
        internal static string ConfirmEndSession {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ConfirmEndSession);
				#else
				return ResourceManager.GetString("ConfirmEndSession", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the game?.
        /// </summary>
        internal static string ConfirmExitGame {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ConfirmExitGame);
				#else
				return ResourceManager.GetString("ConfirmExitGame", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start the game,
        ///even though not all players are ready?.
        /// </summary>
        internal static string ConfirmForceStartGame {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ConfirmForceStartGame);
				#else
				return ResourceManager.GetString("ConfirmForceStartGame", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this session?.
        /// </summary>
        internal static string ConfirmLeaveSession {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ConfirmLeaveSession);
				#else
				return ResourceManager.GetString("ConfirmLeaveSession", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online gameplay is not available in trial mode.
        ///Would you like to purchase this game?.
        /// </summary>
        internal static string ConfirmMarketplace {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ConfirmMarketplace);
				#else
				return ResourceManager.GetString("ConfirmMarketplace", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit this game?.
        /// </summary>
        internal static string ConfirmQuitGame {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ConfirmQuitGame);
				#else
				return ResourceManager.GetString("ConfirmQuitGame", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Flatware Design 2011.
        /// </summary>
        internal static string Copyright {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Copyright);
				#else
				return ResourceManager.GetString("Copyright", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        internal static string CreateSession {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.CreateSession);
				#else
				return ResourceManager.GetString("CreateSession", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string Easy {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Easy);
				#else
				return ResourceManager.GetString("Easy", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Session.
        /// </summary>
        internal static string EndSession {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.EndSession);
				#else
				return ResourceManager.GetString("EndSession", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the network session.
        /// </summary>
        internal static string ErrorDisconnected {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorDisconnected);
				#else
				return ResourceManager.GetString("ErrorDisconnected", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign in a suitable gamer profile
        ///in order to access this functionality.
        /// </summary>
        internal static string ErrorGamerPrivilege {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorGamerPrivilege);
				#else
				return ResourceManager.GetString("ErrorGamerPrivilege", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host ended the session.
        /// </summary>
        internal static string ErrorHostEndedSession {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorHostEndedSession);
				#else
				return ResourceManager.GetString("ErrorHostEndedSession", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while
        ///accessing the network.
        /// </summary>
        internal static string ErrorNetwork {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorNetwork);
				#else
				return ResourceManager.GetString("ErrorNetwork", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking is turned
        ///off or not connected.
        /// </summary>
        internal static string ErrorNetworkNotAvailable {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorNetworkNotAvailable);
				#else
				return ResourceManager.GetString("ErrorNetworkNotAvailable", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host kicked you out of the session.
        /// </summary>
        internal static string ErrorRemovedByHost {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorRemovedByHost);
				#else
				return ResourceManager.GetString("ErrorRemovedByHost", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session is already full.
        /// </summary>
        internal static string ErrorSessionFull {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorSessionFull);
				#else
				return ResourceManager.GetString("ErrorSessionFull", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found. It may have ended,
        ///or there may be no network connectivity
        ///between the local machine and session host.
        /// </summary>
        internal static string ErrorSessionNotFound {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorSessionNotFound);
				#else
				return ResourceManager.GetString("ErrorSessionNotFound", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait for the host to return to
        ///the lobby before you can join this session.
        /// </summary>
        internal static string ErrorSessionNotJoinable {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorSessionNotJoinable);
				#else
				return ResourceManager.GetString("ErrorSessionNotJoinable", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to store rankings. Try again?.
        /// </summary>
        internal static string ErrorStoreRankings {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorStoreRankings);
				#else
				return ResourceManager.GetString("ErrorStoreRankings", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is not available in trial mode.
        /// </summary>
        internal static string ErrorTrialMode {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorTrialMode);
				#else
				return ResourceManager.GetString("ErrorTrialMode", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        internal static string ErrorUnknown {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ErrorUnknown);
				#else
				return ResourceManager.GetString("ErrorUnknown", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Exit);
				#else
				return ResourceManager.GetString("Exit", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Sessions.
        /// </summary>
        internal static string FindSessions {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.FindSessions);
				#else
				return ResourceManager.GetString("FindSessions", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER!.
        /// </summary>
        internal static string GameOver {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.GameOver);
				#else
				return ResourceManager.GetString("GameOver", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string Hard {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Hard);
				#else
				return ResourceManager.GetString("Hard", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (host).
        /// </summary>
        internal static string HostSuffix {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.HostSuffix);
				#else
				return ResourceManager.GetString("HostSuffix", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready.
        /// </summary>
        internal static string IsNotReady {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.IsNotReady);
				#else
				return ResourceManager.GetString("IsNotReady", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready!.
        /// </summary>
        internal static string IsReady {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.IsReady);
				#else
				return ResourceManager.GetString("IsReady", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ⓐ Join.
        /// </summary>
        internal static string JoinInstruction {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.JoinInstruction);
				#else
				return ResourceManager.GetString("JoinInstruction", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Session.
        /// </summary>
        internal static string JoinSession {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.JoinSession);
				#else
				return ResourceManager.GetString("JoinSession", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Session.
        /// </summary>
        internal static string LeaveSession {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.LeaveSession);
				#else
				return ResourceManager.GetString("LeaveSession", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Level);
				#else
				return ResourceManager.GetString("Level", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Loading);
				#else
				return ResourceManager.GetString("Loading", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string Lobby {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Lobby);
				#else
				return ResourceManager.GetString("Lobby", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string Local {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Local);
				#else
				return ResourceManager.GetString("Local", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MainMenu {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.MainMenu);
				#else
				return ResourceManager.GetString("MainMenu", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Ⓐ Ok
        ///Ⓑ Cancel.
        /// </summary>
        internal static string MessageBoxUsage {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.MessageBoxUsage);
				#else
				return ResourceManager.GetString("MessageBoxUsage", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined.
        /// </summary>
        internal static string MessageGamerJoined {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.MessageGamerJoined);
				#else
				return ResourceManager.GetString("MessageGamerJoined", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left.
        /// </summary>
        internal static string MessageGamerLeft {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.MessageGamerLeft);
				#else
				return ResourceManager.GetString("MessageGamerLeft", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking....
        /// </summary>
        internal static string NetworkBusy {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.NetworkBusy);
				#else
				return ResourceManager.GetString("NetworkBusy", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries.
        /// </summary>
        internal static string NoEntries {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.NoEntries);
				#else
				return ResourceManager.GetString("NoEntries", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Normal);
				#else
				return ResourceManager.GetString("Normal", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sessions found.
        /// </summary>
        internal static string NoSessionsFound {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.NoSessionsFound);
				#else
				return ResourceManager.GetString("NoSessionsFound", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Paused);
				#else
				return ResourceManager.GetString("Paused", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        internal static string PlayerMatch {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.PlayerMatch);
				#else
				return ResourceManager.GetString("PlayerMatch", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ⓐ Continue.
        /// </summary>
        internal static string PressAToContinue {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.PressAToContinue);
				#else
				return ResourceManager.GetString("PressAToContinue", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string QuitGame {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.QuitGame);
				#else
				return ResourceManager.GetString("QuitGame", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings.
        /// </summary>
        internal static string Rankings {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Rankings);
				#else
				return ResourceManager.GetString("Rankings", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        internal static string ResumeGame {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ResumeGame);
				#else
				return ResourceManager.GetString("ResumeGame", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Lobby.
        /// </summary>
        internal static string ReturnToLobby {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ReturnToLobby);
				#else
				return ResourceManager.GetString("ReturnToLobby", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Score);
				#else
				return ResourceManager.GetString("Score", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage {0}.
        /// </summary>
        internal static string Stage {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Stage);
				#else
				return ResourceManager.GetString("Stage", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Link.
        /// </summary>
        internal static string SystemLink {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.SystemLink);
				#else
				return ResourceManager.GetString("SystemLink", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Time);
				#else
				return ResourceManager.GetString("Time", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ⓧ Toggle.
        /// </summary>
        internal static string ToggleReady {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.ToggleReady);
				#else
				return ResourceManager.GetString("ToggleReady", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Total);
				#else
				return ResourceManager.GetString("Total", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versus AI.
        /// </summary>
        internal static string VersusAI {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.VersusAI);
				#else
				return ResourceManager.GetString("VersusAI", resourceCulture);
				#endif
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        internal static string Wins {
            get {
				#if __ANDROID__
				return Android.App.Application.Context.Resources.GetString(Resource.String.Wins);
				#else
				return ResourceManager.GetString("Wins", resourceCulture);
				#endif
            }
        }
    }
}
